In [15]:
import pandas as pd
import numpy as np
import duckdb
import matplotlib.pyplot as plt
import seaborn as sns
import json
import os
import re
import sys
from glob import glob
from IPython.display import display, clear_output
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [2]:
con = duckdb.connect(
    database = "../data/MIG_Cement_Records.db",
    read_only = True
)

In [5]:
query = """

        SELECT
            table_schema, table_name
        FROM
            information_schema.tables
        ORDER BY
            table_schema, table_name;

"""

result = con.execute(query).df()

In [6]:
result

  table_schema   table_name
0         main  CementTypes
1         main   Operations
2         main        Sites

In [23]:
def table_schema(table_name: str) -> None:
    query = f"""
    
                SELECT
                    column_name,
                    data_type
                FROM
                    information_schema.columns
                WHERE
                    table_name == '{table_name}'
    """

    result = con.execute(query).df()

    display(result)

In [24]:
table_schema("CementTypes")

   column_name data_type
0  cement_type   VARCHAR

In [25]:
table_schema("Operations")

                 column_name data_type
0                       date   VARCHAR
1                    site_id   VARCHAR
2                cement_type   VARCHAR
3        planned_pour_tonnes    DOUBLE
4            consumed_tonnes    DOUBLE
5   opening_inventory_tonnes    DOUBLE
6          deliveries_tonnes    DOUBLE
7   closing_inventory_tonnes    DOUBLE
8                    rain_mm    DOUBLE
9                 avg_temp_c    DOUBLE
10             silo_capacity    BIGINT

In [26]:
table_schema("Sites")

     column_name data_type
0        site_id   VARCHAR
1         region   VARCHAR
2  silo_capacity    BIGINT
3       behavior   VARCHAR